// authApi.js
// Thin wrappers around auth-related BE endpoints — no business logic, just call + return.
//
// Intentionally uses httpClient (not api.js): auth endpoints must NOT trigger the
// 401 refresh-retry interceptor in api.js, which would cause a recursive refresh loop
// if the verify or refresh endpoints themselves returned 401.

import httpClient from '../../../shared/services/httpClient';

const authApi = {
  // Verifies an email activation token generated by the BE after user registration.
  // GET /api/v1/auth/verify?token=<activation_token>
  // The token value is read from the URL query param on the VerifyEmailPage route.
  verifyAccount: (token) => {
    return httpClient.get('/auth/verify', { params: { token } });
  },
};

export default authApi;